### ISSUE TITLE
课程时间地点查询不到

### ISSUE THREAD

**Issue by Ming-Yang** [yaowenxu/Classes-Selection#8]
其他学院的课，课程信息没写，也查不到排课，如何找到呢
课程号：001714

**Comment by Baioi** [comment]
哪个学院开的课啊？

**Comment by yaowenxu** [comment]
你找找其他学院的同学，咱们硕士微信群，不是还有几个其他学院的人吗。他们可能排课可能会随着选课人数变动。

**Comment by Ming-Yang** [comment]
> 
> 
> 自动化的 排课上我也没查到

所以得我们自己找同学问？
